version: '3.8'

services:
  id-verification:
    build: .
    ports:
      - "3000:3000"
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
    volumes:
      - ./server/models:/app/server/models
    restart: unless-stopped 